include:
  - project: sennder/engineering-effectiveness/platform/sennder-gitlab-templates
    file: python-publish-registry.yml
  - project: sennder/engineering-effectiveness/platform/platform-libs/container-images/semantic-release
    file:
      - /gitlab-ci-templates/self-service-prepare.yaml
      - /gitlab-ci-templates/pick-and-use.yaml

stages:
  - semantic-release-prepare
  - semantic-release

semantic_release:
  stage: semantic-release
  extends: .semantic_release
  before_script:
    - !reference [.prepare_pip, before_script]
    - apk add --no-cache --update python3 py3-pip
    - pip3 install twine wheel
